version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      actions-deps:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/cloud-agent/client/generator"
      - "/cloud-agent/client/typescript"
      - "/prism-node/client/scala-client/api/grpc"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      npm-prod-deps:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directories:
      - "/tests/didcomm-tests"
      - "/tests/performance-tests/agent-performance-tests-k6"
    schedule:
      interval: "monthly"
      day: "monday"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      npm-test-deps:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directories:
      - "/examples/st-oid4vci/demo"
    schedule:
      interval: "monthly"
      day: "monday"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      docker-demo-deps:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directories:
      - "/examples/st-oid4vci/demo"
    schedule:
      interval: "monthly"
      day: "monday"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      pip-demo-deps:
        patterns:
          - "*"